title: 'HERD Collaboration WebSite'
default_lang: null
author:
  name: 'Matteo Duranti, Maura Graziani'
  email: matteo.duranti@infn.it
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
