title: 'HERD Perugia'
default_lang: null
author:
  name: 'Matteo Duranti, Maura Graziani'
  email: bozzo1983@gmail.com
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
