#!/bin/bash

echo "---"
echo "title: 'HERD Wiki - Version $1'"
#echo "sitemap:"
#echo "    changefreq: monthly"
echo "body_classes: 'header-dark header-transparent'"
echo "hero_classes: 'text-light title-h1h2 overlay-dark-gradient hero-large parallax'"
echo "hero_image: mountain.jpg"
#echo "custom: 'new thing'"
#echo "wiki_url: /wiki"
echo "show_sidebar: true"
echo "sidebar_root: $1"
#echo "content:"
#echo "    items:"
#echo "        - '@self.children'"
#echo "    limit: 6"
#echo "    order:"
#echo "        by: date"
#echo "        dir: desc"
#echo "    pagination: false"
#echo "    url_taxonomy_filters: false"
#echo "feed:"
#echo "    description: 'Sample Blog Description'"
#echo "    limit: 10"
#echo "pagination: true"
echo "process:"
echo "    markdown: true"
echo "    twig: false"
echo "twig_first: false"
echo "---"
